### ISSUE TITLE
any idea how compiling it?

### ISSUE THREAD

**Issue by letarg0** [mozeal/SDL_gui#1]
How using example?

**Comment by mozeal** [comment]
In each examples (Tests directory) has the directory for each platform.

- MacOSX - use Xcode open the *.xcodeproj then compile and run
- iOS - use Xcode open the *.xcodeproj then compile and run
- Android - use android studio open the _Android directory then compile and run it. You may need to config the local.properties to specific sdk and ndk directories.
- Windows - use Visual Studio 2017 open the *.sln then compile and run. You need to use vspkg to install HarfBuzz first.
- Emscripten - run make (you need to set path for emsdk tools first)
- Cmake - just run cmake then make.
