### ISSUE TITLE
Why do you don't develop this great library?!?

### ISSUE THREAD

**Issue by SzykCech4** [mozeal/SDL_gui#4]
Hi
In the past I was great enthusiast Qt library, but when I start develop mobile app I realize that they betray C++ in flavor to lame JavaScript (they call it Qml for some reason - maybe due to the fact it is even more painfull and stupid than true JavaScript known from WWW world).
Any way I look for alternatives to Qt. And there is pity in C++ word. I don't found any other lib than SDL to be true multiplatform (desktop, mobile and embeded). In the past I encountered some GUI libs for SDL so now I decide to investigate this area today. That is the way I found your great library!

I want to encourage you do futher develop this library - be ware: competitor incomming: https://neogfx.org/ - but they do the same cheat as Qt, M$ and Borland - proprietriary (scripting) language. This is unaceptable! So I suggest to you to make futher development in order to save C++ word! Dont let phase out this powerfull language in flavor to mad/idiotic virtual machines and some other interpreters. I can't imagine why some idiot decide to implement mobile OS in virtual machine based language?!? (mean: Android). We need full speed, portability and minimal power consumption. In C++ word this offer only SDL!

You can start from these points:
1. Fixing CMakeLists.txt for most tests: they lacks ../../../SDL2_gui/GUI_Config.cpp file in SOURCE_FILES variable.
1.1. Remove from tests ./src/SDL2_gfx and ./src/SDL2_gui - they are not used - every sources are from project root directory.
2. Write examples: workable common scenarios, like this:
2.1. How implement mouse and keyboard interactions
2.2. How to make float/dragable windows - is this even possible?!?.
3. Make CMakeLists.txt for SDL2_gui library in order to not include all the time every separate *.o files
4. Documentation:
4.1. How to setup development enviroment?!? Some auotmatic script will be welcome.
4.2. What is recomended IDE to write apps with SDL2_gui?!? For now I use Qt Creator - but is this optimal?!?
4.3. How to internationalize SDL2_gui based apps?!?
4.4 Is this posbile to use SDL2 in GDI mode?!? I mean: can it works with remote desktops?!?
5. Use Cmake for all subprojects (phase out makefiles and autotools - they are obscure and not portable).

I don't mean that you should wrote monster library like Qt.
I mean: SDL2_gui can be smal but, blast fast, smart and programmer friendly.
Remember: 90% language goodnes lies in its libraries. That is the reason why SDL2_gui is important.

If you like I can offer my help in SDL2_gui development area:
I am experienced with Cmake, C++11, native C Linux/X11 Apis, and Windows Apis, and also some how with Android (from Qt projects point of view). I want program multiplatform and multilingual in C++ with SDL2_gui.
How ever I have no experience with SDL - I mainly work with Qt.
But I am not sure if I will have enough free time, because in monday (2019-06-03) I will start new job, and I supose it will be wise to spend some of my free time to acustom with new enviroment/organization.

**Comment by mozeal** [comment]
Thanks for your encouraging me to continue on this project. Yes, I will do as your suggest. I'm very appreciated if you can help on CMake issues. I'm not using Cmake frequently, so, that's very difficult for me.

I've added you as contributor to this project. please help.
